export const Data = [
  {
    id: "1",
    name: "Running-Shoes-blue",
    description: "Wear to Comfortable",
    src: "images/shoes1.png",
    price: 120,
    Quantity: 1,
  },
  {
    id: "2",
    name: "Running-shoes-black",
    description: "Wear to  Comfortable",
    src: "images/shoes2.png",
    price: 120,
    Quantity: 1,
  },
  {
    id: "3",
    name: "Shoes-Sneaker",
    description: "Wear to Comfortable",
    src: "images/shoes3.png",
    price: 120,
    Quantity: 1,
  },
  {
    id: "4",
    name: "shoes-black",
    description: "Wear to Comfortable",
    name: "Running-shoes-black",
    src: "images/shoes4.png",
    price: 120,
    Quantity: 1,
  },
  {
    id: "5",
    name: "Running-shoes-black",
    description: "Wear to Comfortable",
    src: "images/shoes5.png",
    price: 120,
    Quantity: 1,
  },
  {
    id: "6",
    name: "Green-Shirt",
    description: "Wear to Stylish & Comfortable",
    src: "images/tisat1.png",
    price: 120,
    Quantity: 1,
  },
  {
    id: "7",
    name: "Mustard-Shirt",
    description: "Wear to Stylish & Comfortable",
    src: "images/tisat2.png",
    price: 120,
    Quantity: 1,
  },
  {
    id: "8",
    name: "Polo-Shirt",
    description: "Wear to Stylish & Comfortable",
    src: "images/tisat3.png",
    price: 120,
    Quantity: 1,
  },
  {
    id: "9",
    name: "Red-Shirt",
    description: "Wear to Stylish & Comfortable",
    src: "images/tisat4.png",
    price: 120,
    Quantity: 1,
  },
  {
    id: "10",
    name: "Casual-Shirt",
    description: "Wear to Stylish & Comfortable",
    src: "images/tisat5.png",
    price: 120,
    Quantity: 1,
  },
  {
    id: "11",
    name: "Mobile",
    description: "Good Locking",
    src: "images/mix1.png",
    price: 120,
    Quantity: 1,
  },
  {
    id: "12",
    name: "Casual-Glasses",
    description: "Good Locking",
    src: "images/mix2.png",
    price: 120,
    Quantity: 1,
  },
  {
    id: "13",
    name: "Shaving-Machine",
    description: "Use For Better Result",
    src: "images/mix3.png",
    price: 120,
    Quantity: 1,
  },
  {
    id: "14",
    name: "Watch",
    description: "Good Locking",
    src: "images/mix4.png",
    price: 120,
    Quantity: 1,
  },
  {
    id: "15",
    name: "HeadPhone",
    description: "Sound Quality is Better",
    src: "images/mix5.png",
    price: 120,
    Quantity: 1,
  },
];
